name: Build XNU Kernel

on: [push]

jobs:
  build:
    runs-on: macos-14 # Must be macOS to have Xcode and XNU build tools
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

     - name: Setup tmate session
       uses: mxschmitt/action-tmate@v3
        with:
          # This forces tmate to generate a new key for this session
          limit-access-to-actor: false

      - name: Build XNU
        env:
          CI: "true"
          DEBIAN_FRONTEND: "noninteractive"
        run: |
          # If ./build.sh still fails, this SSH session will stay open
          # so you can run it manually and debug the menu
          chmod +x build.sh
          ./build.sh

      - name: Upload Kernel Artifact
        uses: actions/upload-artifact@v4
        with:
          name: xnu-kernel-binary
          path: output/
